[tool.pyright]

pythonVersion = "3.11"
pythonPlatform = "Windows"


[tool.pytest.ini_options]
log_cli=true
log_level="INFO"

[tool.local_lfs]
dest_path= "C:\\coding\\rodrigogama1902\\local-lfs\\LFS"
include=["tests/fixtures/"]


