[tool.pyright]

reportMissingImports = true
reportMissingTypeStubs = true
reportGeneralTypeIssues = "error"
reportOptionalMemberAccess = true
reportOptionalSubscript = true
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportAttributeAccessIssue = false

pythonVersion = "3.11"
pythonPlatform = "Windows"


[tool.pytest.ini_options]
log_cli=true
log_level="INFO"